### ISSUE TITLE
Butterfree Gmax move giving random players status effects on their pokemon even if you are not battling them.

### ISSUE THREAD

**Issue by ThisGuyIsCute** [Dysth/Generations#103]
**What is the bug?**
So basically the butterfree gmax move is giving status effects to random people on the server aswell.

**What are the steps to reproduce the bug?**
Use the Butterfree Gmax move In a battle.

**What version of Pixelmon and Forge are you on?**
Technic version 8.4.2

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Dysth** [comment]
Hiya,
Can't seem to reproduce this- could you provide your debug.log when this happens so we can see if there's an error?
