### ISSUE TITLE
Buggy Flight

### ISSUE THREAD

**Issue by PePlayer** [Dysth/Generations#120]
**What is the bug?**
I can’t go more than about 100 blocks from my house without my Braviary’s flight getting laggy and sporadic.

**What are the steps to reproduce the bug?**
Go more than 100 blocks from your spawnpoint.

**What version of Pixelmon and Forge are you on?**
1.12.2 Pixelmon and Forge 14.23.5.2855

**Please provide any screenshots or crash reports if needed.**
I don’t have any screenshots and my game hasn’t crashed due to the bug.

**Comment by Stampede2011** [comment]
I cannot reproduce this issue! Are you able to provide a video of some sort?
