### ISSUE TITLE
Cosmog shiny sprite glitch

### ISSUE THREAD

**Issue by VerySneekyMan** [Dysth/Generations#123]
**What is the bug?**
Cosmogs shiny sprite is its normal party sprite

**What are the steps to reproduce the bug?**
Catch a shiny and normal cosmog, put them in party

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.4.2 Forge 14.23.5

**Please provide any screenshots or crash reports if needed.**
![javaw_mz0d3S5fH4](https://user-images.githubusercontent.com/83484141/116768284-746f3100-aa03-11eb-8d3c-2fbed539cb6c.png)

**Comment by Stampede2011** [comment]
For me on version 8.4.2, the sprites are different but by only a few pixels being changed from blue to red. Your screenshot is very weird considering the shiny icon isn't even appearing next to the name
