### ISSUE TITLE
/pokeedit for changing ability doesn't work

### ISSUE THREAD

**Issue by Tomu1572** [Dysth/Generations#142]
**What is the bug?**
Clear description of what the bug is

The command /pokeedit *playername* slot ability: ...... doesn't work. If I tried to change the pokemons ability it would just failed.

**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug

try to use /pokeedit command for changing ability

**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version

8.4.2, forge1.12.2-14.23.5.2847

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Stampede2011** [comment]
Can verify this one. The issue I believe extends from the use of the old `com.pixelmonmod` classes. 

Line 398 of the PokeEdit command class still has: `Class.forName("com.pixelmonmod.pixelmon.entities.pixelmon.abilities." + ball)` where it should be more like `Class.forName("com.pixelmongenerations.common.entity.pixelmon.abilities." + ball)`

**Comment by Stampede2011** [comment]
Should have been fixed for the release in the Owners Discord
