### ISSUE TITLE
Pre-evolutions G-max factor

### ISSUE THREAD

**Issue by Azazel-mp** [Dysth/Generations#150]
In case I remember wrong, didn't pay too much attention while playing Pokemon Sw/Sh, I'll just close this suggestion.

The pre-evolved forms of G-max pokemon should also show the G-max factor if they have it (ex: You can find a wild Grookey with a G-max factor and train him to have a G-max Rillaboom)

p.s. Not sure if it's a bug or only /pokespawn isn't subjected to it, but setting "gmaxFactorSpawnRate" config to 1 doesn't make every g-maxable pokemon spawn with the factor.

**Comment by Deltric** [comment]
Just spent a couple minutes looking around for that and I couldn't find anything about it. If you could send any trusted Pokemon source for it that would be great. As for Poke Spawn that's a command where you build a Pokemon to spawn and not a accurate way of testing wild spawn stuff.

**Comment by Azazel-mp** [comment]
> Just spent a couple minutes looking around for that and I couldn't find anything about it. If you could send any trusted Pokemon source for it that would be great. As for Poke Spawn that's a command where you build a Pokemon to spawn and not a accurate way of testing wild spawn stuff.

Sorry, I tried to look a bit too but, apart from here:
https://m.bulbapedia.bulbagarden.net/wiki/Gigantamax#Acquisition
(where it says Kanto starters, Milcery and Hattrem are the only "normal" pokemon that can have it)
and here:
https://international-pokedex.fandom.com/wiki/Gigantamax_Factor
couldn't find any reliable info about it.

I'll try to play and check some walkthroughs hoping to find some useful images.

**Comment by ModernSilver** [comment]
Just thought I'd throw my hat in the ring real quick. Pre-evolved forms of eligible pokemon will show the G-max factor on the screen. This is the [charmander](https://www.dropbox.com/s/r4h5i7mlkjf1psd/Screenshot_20210603-192549_Pokmon%20HOME.jpg?dl=0) that you get at the end of SW/SH's main story that is capable of Gigantamax (that I've been neglecting to evolve). Screenshot taken from Pokemon Home, but I can transport him to Sword to show you how it looks there if need be.
