### ISSUE TITLE
Permanent Night 

### ISSUE THREAD

**Issue by N4M3LE5S** [Dysth/Generations#165]
The moon will move but then glitch back to one spot making it never become day. It also happens in new worlds

**Comment by Deltric** [comment]
Please follow the provided template and list any additional mods you have installed if any. This is an issue that has never occurred so if you could please be as descriptive as possible with details that could influence this.

**Comment by Stampede2011** [comment]
Please also check if you have the `useSystemTimeForWorldTime` setting set to true in the `pixelmon.hocon` config file. If it's set to true, it will match the world time to your system's time.
