### ISSUE TITLE
Enemy Health Bar Visual Glitch

### ISSUE THREAD

**Issue by Soukply** [Dysth/Generations#204]
**What is the bug?**
In the GUI of battle's, there is a small but not unnoticeable chance that the enemy's health bar has a visual glitch where the green bar extends to the end of the surround grey box towards the right hand side.

**What are the steps to reproduce the bug?**
Unclear, in my own testing, and testing from your helper A_Fish【CM】that it seems to only come up in Custom made NPC Trainer Battles. I personally saw it on 3 in a very short time span (30mins roughly)

**What version of Pixelmon and Forge are you on?**
Latest version (8.5.1) and the server is running forge-1.12.2-14.23.5.2847-universal.jar

**Please provide any screenshots or crash reports if needed.**
Also saw it on a Piplup so we know its not Munchlax exclusive
![image](https://user-images.githubusercontent.com/86370871/123133775-700b4580-d493-11eb-9ee6-2f99c1643bf3.png)

**Comment by Stampede2011** [comment]
I believe this has been fixed :)
