### ISSUE TITLE
Level 0 Trainers

### ISSUE THREAD

**Issue by Cavans99** [Dysth/Generations#208]
**What is the bug?**
Wild Groomers spawn as level 0 Trainers. (new world and configs regenerated)

**What are the steps to reproduce the bug?**
Sometimes a Lv.0 trainer spawns in the wild.
It spawned in older versions too, but couldn't be battled at all, while in latest version it can be battled, showing "Groomer:" as dialogue line and then stalling the battle until you run away.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.5.1, Forge 14.23.5.2855

**Please provide any screenshots or crash reports if needed.**
![Groomer](https://user-images.githubusercontent.com/81328680/125164165-2c9e2000-e191-11eb-96e9-82df093ef8f9.png)

**Comment by AkashaP** [comment]
im having a lot of these spawn, in many biomes with biomes o plenty
