### ISSUE TITLE
Shiny Charm/Catch Combos do not boost static encounters (legendary shrines, zygarde creatio, fossil machine, etc.)

### ISSUE THREAD

**Issue by JakeBlack2003** [Dysth/Generations#216]
**What is the bug?**
The shiny charm and/or catch combo shiny rates do not affect zygarde, fossil, or shrine encounters. From my testing those are only affected by the base shiny rate in the config, and nothing else will boost it.

**What are the steps to reproduce the bug?**
In the config, set your tier 1 catch combo shiny odds to 1 along with your shiny charm odds to 1 as well, this will make shinies guaranteed. Then get a tier 1 catch combo or the shiny charm and go to either a shrine, zygarde machine, or fossil machine and make a Pokémon from it, it will not be shiny.

**What version of Pixelmon and Forge are you on?**
Pixelmon: 8.5.1
Forge: 14.23.5.2855

**Comment by Stampede2011** [comment]
Fixed in version 8.6.1
