### ISSUE TITLE
Battle GUI Bug

### ISSUE THREAD

**Issue by BlueMalarkey62** [Dysth/Generations#217]
**What is the bug?**
To make this as clear as I can, I initiate a battle with an NPC, then I choose an attack and after that, the battle ends.

**What are the steps to reproduce the bug?**
1. Initiate a Battle with an NPC
2. Choose an Attack
3. Your battle will end abruptively due to a bug

**What version of Pixelmon and Forge are you on?**
1.12.2

**Please provide any screenshots or crash reports if needed.**
![2021-07-28_19 30 05](https://user-images.githubusercontent.com/74742276/127417559-2f43e90d-7394-4135-b0f9-c1cdfa86f0b7.png)

**Comment by BlueMalarkey62** [comment]
Update 1: I figured out that it's the AFK Handler

AFK battle is set to 20 seconds
AFK turns is set to 2 seconds

**Comment by BlueMalarkey62** [comment]
Update 2: This bug only happens if the NPC AI is set to advanced. This is the result of another test.

**Comment by BlueMalarkey62** [comment]
Update 3: If it's a 1v1 battle with the same Pokemon, i.e., Pikachu, it gets stuck on "waiting" and you have to do /endbattle.

**Comment by Stampede2011** [comment]
I cant seem to replicate this in the latest version, so this likely has been fixed!
