### ISSUE TITLE
Bug with Mean Look

### ISSUE THREAD

**Issue by Freewill97** [Dysth/Generations#229]
**What is the bug?**
Mean Look does not stop Abras from teleporting away. 

**What are the steps to reproduce the bug?**
Use Gastly to catch Abras underground in the Meadows biome. Use Mean Look and the Abras and Kadabras will still teleport away.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.4.2 and Forge 14.23.5.2855 on 1.12.2.

**Please provide any screenshots or crash reports if needed.**
I think it's pretty self-explanatory. Mean Look doesn't work for me. Doesn't stop it from being able to teleport away.

**Comment by Stampede2011** [comment]
Fixed in version 8.6.1
