### ISSUE TITLE
Pokemon are invisible 

### ISSUE THREAD

**Issue by Woopy123** [Dysth/Generations#243]
**What is the bug?**
Clear description of what the bug is
So almost half of all pokemon are invisble and i cant put tm or give rare candy to the invisble fossil poke i have, and wild pokemon most of them are invisible so i just randomly walk into them and all legendary pokemon are invisble.

**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug
so i tried restarting my computer and minecraft didnt work, then i tried restarting my graphic drivers didnt work, and i tried reinstalling pixelmon didnt work.

**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version
im on pixelmon generations 8,5,1 and forge 1.12,2 forge 14,23,5,2855

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug
![2021-09-04_15 11 43](https://user-images.githubusercontent.com/90097983/132095668-50c081f6-9b1f-45ff-aca8-5105395275b6.png)

**Comment by Woopy123** [comment]
the pokemon is infront of me

**Comment by Invisible229** [comment]
I had such an error... this mod may require an additional mod, then the textures will work... if you have a license, you can download the assembly for this mod, there will be no errors or re-download it for a specific mod, perhaps you did something that made it invisible, in which case, just return the original file of this or that pokemon...

this is how the mod package looks like, you can download it here for this you need a launcher: https://www.technicpack.net/modpack/pixelmon-513-pro.1072839
to find you write: Pixelmon Generations

**Comment by Dysth** [comment]
Hi, Make sure you are using Java 1.8 64 bit (offline)
https://www.java.com/en/download/manual.jsp
Download: Windows Offline (64-bit)
and uninstall the 32 bit versions you may have uninstalled
