### ISSUE TITLE
kicked into the launcher immediately 

### ISSUE THREAD

**Issue by Reqwan** [Dysth/Generations#256]
**What is the bug?**
Clear description of what the bug is
getting kicked back into the launcher
**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug
play the mod for about 5 minutes
**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version
generations 8.5.1
**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug
can't screenshot it kicks me without any dialogue

**Comment by Stampede2011** [comment]
@Reqwan are you still experiencing this issue?
