### ISSUE TITLE
Excluded and duplicated pokemons

### ISSUE THREAD

**Issue by Pedro92007** [Dysth/Generations#26]
**What is the bug?**
I'm playing with my friends and some pokemons (on PC) were excluded and others were duplicated. The same mew was in my party and my friend's party.

**What are the steps to reproduce the bug?**
I don't know. We recently cloned mew into Mewtwo and Ditto, and my friends used the ranch machine, so we closed the serves (we play in a solo world and they connected in radmin). Then we open the servers in the next morning and these bugs occurred.

**What version of Pixelmon and Forge are you on?**
8.4.1 (the newest at the time in Technic

**Please provide any screenshots or crash reports if needed.**
I don't have any

**Comment by Stampede2011** [comment]
An attempted fixed was implemented in 8.6.1
