### ISSUE TITLE
Generations Shrine mistype

### ISSUE THREAD

**Issue by Cavans99** [Dysth/Generations#267]
**What is the bug?**
A mistype in the `generations_group.json` file causes the game to crash.

**What are the steps to reproduce the bug?**
In line 7 of `generations_group.json` file, Ho-Oh has been listed as `"species": "Hooh"`, so when rolled it causes the game/server to crash.
Changing it in `"species": "Ho-Oh"` fixes the issue.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.6.0, Forge 14.23.5.2855

**Please provide any screenshots or crash reports if needed.**

**Comment by Stampede2011** [comment]
Fixed in version 8.6.1
