### ISSUE TITLE
infinite level up keys

### ISSUE THREAD

**Issue by wesdar** [Dysth/Generations#271]
im currently at 
X 12178
Y 65
Z -14406
i dont know if this is possible somewhere else, but when i click the pokeball chest that is here it says i need permission from an administrator to interact with it, but i still get 15 xp, when i spamm click it i level up and get a level up key, i tested spamming to see if it would actually work and it did
minecraft 1.12.2 
forge 14.23.5.2847

**Comment by Cavans99** [comment]
Looks like you are talking about a specific server, try to report it in their discord.
