### ISSUE TITLE
Suggestion: Map mod

### ISSUE THREAD

**Issue by FallenAzazael** [Dysth/Generations#281]
I feel like this game would be a lot more user friendly with some sort of live map. I used  to play reforged a lot but switched to generations and i love it, but i miss the map. i tried installing it myself but could not get it to work on my own pc.

**Comment by Cavans99** [comment]
If you mean you want pokemon on the minimap it's already possible with Generations Buddy!
https://pixelmongenerations.com/wiki/index.php?title=GenerationsBuddy
