### ISSUE TITLE
Couch crafting recipes

### ISSUE THREAD

**Issue by Cavans99** [Dysth/Generations#286]
**What is the bug?**
Although all couch pieces appear to have the right crafting recipes when checking with JEI mod, if you try to craft a Left couch part (corner or arm) it always gives the Right corresponding part.

**What are the steps to reproduce the bug?**
Try to craft left couch pieces.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.6.1, Forge 14.23.5.2858

**Please provide any screenshots or crash reports if needed.**

**Comment by Cavans99** [comment]
p.s. I also noticed some crafting recipes are still missing, here's my suggestion for them:
[Recipes.zip](https://github.com/Dysth/Generations/files/7741694/recipes.zip)

**Comment by Asberebunch** [comment]
.
