### ISSUE TITLE
Pixelmon Spawner shininess

### ISSUE THREAD

**Issue by Cavans99** [Dysth/Generations#297]
**What is the bug?**
If a new pokemon is added to a Pixelmon Spawner and its Shiny field is set to 1 (1/1 chance to spawn as a shiny) it will only spawn in its normal texture.
Every other number works as intended.

**What are the steps to reproduce the bug?**
While setting up a Pixelmon Spawner, change the Shiny field to 1 and add a new pokemon to the list, the pokemon should always spawn in its shiny form, but it doesn't.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.6.1, Forge 14.23.5.2858

**Please provide any screenshots or crash reports if needed.**

**Comment by Stampede2011** [comment]
I believe this is caused by a fix for a different bug that was happening. To keep that bug from happening this might have to stay for now
