### ISSUE TITLE
Exp. Charm drop chance

### ISSUE THREAD

**Issue by Cavans99** [Dysth/Generations#304]
**What is the bug?**
(Bug reported in the Discord)
Setting `expCharmMaxChance` to 0 or lower should disable the Exp. Charm from having a chance to be dropped, while it doesn't at the moment.

**What are the steps to reproduce the bug?**
In pixelmon.hocon change `expCharmMaxChance` setting to 0, -1 or less, save the file and defeat random pokemon.
The Exp. Charm will still have a chance to be dropped.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.6.1, Forge 14.23.5.2860

**Please provide any screenshots or crash reports if needed.**

**Comment by Stampede2011** [comment]
Should be fixed :)
