### ISSUE TITLE
Articuno movepools

### ISSUE THREAD

**Issue by Cavans99** [Dysth/Generations#306]
**What is the bug?**
Articuno can't learn any move via Move Relearner/Tutor and has and incorrect TM/TR pool.

**What are the steps to reproduce the bug?**
1- If Articuno already knows 4 moves, any other move learned from a Move Relearner/Tutor will appear as "incorrect for this species", the bug doesn't happen if Articuno knew 3 or less moves before interacting with the NPC.
2- Kantonian Articuno TM/TR movepool is swapped with its Galarian version one (ex: Articuno can learn Psychic, Psycho cut, but can't learn Ice beam, Blizzard...)

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.6.2, Forge 14.23.5.2860

**Please provide any screenshots or crash reports if needed.**

**Comment by Jizza221** [comment]
same sort of bug with zapdos also

**Comment by Cavans99** [comment]
And Moltres too apparently

**Comment by Cavans99** [comment]
Forgot to close this. It's fixed.
