### ISSUE TITLE
Compatibility with Jer

### ISSUE THREAD

**Issue by Azazel-mp** [Dysth/Generations#328]
Just enough resources is an useful mod that shows all ways to obtain an item.
Is it possible to make it work with Pixelmon?

**Comment by Lypaka-Dev** [comment]
Sounds like something that mod would have to do, not us. We can't make a mod support our stuff, that's up to that mod's author(s).

**Comment by Azazel-mp** [comment]
oh okay thank you. I will try to contact them once the mod is in 1.18
