### ISSUE TITLE
Pixelmon crash

### ISSUE THREAD

**Issue by Dragonia132** [Dysth/Generations#339]
Hello! someone i know wants to set up a server however they are constantly getting crashes.
They asked me for help and after getting trough a few errors myself and fixing them I got stuck on it when they sent me these crash reports, the first one is with all the mods they are using, second is with only pixelmon in.
[crash-2022-05-10_16.55.06-server.txt](https://github.com/Dysth/Generations/files/8663363/crash-2022-05-10_16.55.06-server.txt)
[crash-2022-05-10_16.55.06-server.txt](https://github.com/Dysth/Generations/files/8663370/crash-2022-05-10_16.55.06-server.txt)

**Comment by Dragonia132** [comment]
> Your Pixelmon Extras version is outdated, update it to make it work with Generations: https://pixelmongenerations.com/wiki/index.php?title=SideMods

Thanks!
However as I said the server also crashes with only generations (and biomes o plenty)
I'm so sorry I didn't realise I uploaded the same crash report twice, this should be the correct one:
https://pastebin.com/F5Dw5jWD

**Comment by Cavans99** [comment]
> Thanks! However as I said the server also crashes with only generations (and biomes o plenty) I'm so sorry I didn't realise I uploaded the same crash report twice, this should be the correct one: https://pastebin.com/F5Dw5jWD

Try updating your Java 8 version, get latest available 64-bit build for Linux:
https://www.java.com/download/manual.jsp
