### ISSUE TITLE
Gym Leader battles don't work properly

### ISSUE THREAD

**Issue by HyruleTeam64** [Dysth/Generations#348]
**What is the bug?**

I tried spawning gyms using the /struc command and their Gym Leader battles don't work, in the first turn nothing will happen after selecting a command and it skips directly to the second turn. When you select a command on the second turn, the battle immediately stops and the message "A battle error has occured" appears in chat. I don't know if it also happens in naturally spawning gyms

**What version of Pixelmon and Forge are you on?**
Forge: 14.23.5.2855
Pixelmon: 8.7.0

**Comment by Stampede2011** [comment]
This should be fixed in 8.7.1
