### ISSUE TITLE
Update the sprites

### ISSUE THREAD

**Issue by sstinky** [Dysth/Generations#373]
**What is the bug?**
Just a small request to improve the looks of the game.

**What version of Pixelmon and Forge are you on?**
8.7.1
**Please provide any screenshots or crash reports if needed.**

![image](https://user-images.githubusercontent.com/108243233/175838472-1ad51a1a-d3cc-4125-92e2-6d310d005014.png)

![image](https://user-images.githubusercontent.com/108243233/175838478-508e28a9-98de-49a4-b069-c19619f1400b.png)

**Comment by Cavans99** [comment]
? They are just two different styles of making the sprites, not much to improve (or fix, as you put this as a bug)?
An improvement would be to change them into something completely different, like PLA did, even tho I'm quite fond of these sprites.

**Comment by Stampede2011** [comment]
As Canvas said, this is just a style difference. We will always update sprites as we see fit, but just saying to update sprites is not super constructive on exactly which should be changed!
