### ISSUE TITLE
Palkia and dialga altered form photo bug

### ISSUE THREAD

**Issue by phoenixlord789** [Dysth/Generations#385]
**What is the bug?**
Clear description of what the bug is

**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug

**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Stampede2011** [comment]
Please re-create a ticket with the proper information filled out.
