### ISSUE TITLE
NPCs can spawn without a body

### ISSUE THREAD

**Issue by Lukeno94** [Dysth/Generations#59]
**What is the bug?**
Occasionally, you will find an NPC has spawned with no model; just a floating message. When trying to edit it with an NPC wand, it will then crash your game.

**What are the steps to reproduce the bug?**
Not 100% sure at this point; I've only seen it happen with random wild NPCs. It almost looks from the crash report that it is trying to load some custom skin but can't.

**What version of Pixelmon and Forge are you on?**
Generations 8.4.2 and Forge 2854

**Please provide any screenshots or crash reports if needed.**
![2021-04-04_12 29 52](https://user-images.githubusercontent.com/81629405/113507360-e3ab4f80-9541-11eb-9bf4-c07b0bb47ab0.png)
[crash-2021-04-04_12.31.16-client.txt](https://github.com/Deltric/Generations/files/6254447/crash-2021-04-04_12.31.16-client.txt)

**Comment by Deltric** [comment]
Do you have external NPCs enabled on the server? Have not seen this issue on servers with up to date external NPCs.

**Comment by Lukeno94** [comment]
As far as I'm aware, we do - Dysthymic should be able to confirm that for certain.
