### ISSUE TITLE
can't ride pokemon in water and can't send out pokemon

### ISSUE THREAD

**Issue by humematt190** [Dysth/Generations#65]
**What is the bug?**
Cannot ride pokemon in water and can't send out pokemon after that

**What are the steps to reproduce the bug?**
keep trying to ride a pokemon while in water then try to send it out on land

**What version of Pixelmon and Forge are you on?**
Pixelmon version 8.4.2 Forge version 14.23.5.2854

**Comment by Deltric** [comment]
Please include more specific information than what you've provided.
