### ISSUE TITLE
/pokeedit for abilities seems broken 

### ISSUE THREAD

**Issue by Abbatoir** [Dysth/Generations#69]
**What is the bug?**
/pokeedit doesn't seem to work for abilities
Says _Ability is invalid or not in Pixelmon!_ even though I'm using tab
I tried different abilities for different Pokemon with 1 or 2 normal abilities + one hidden
 and it never worked

**What are the steps to reproduce the bug?**
Type "_/pokeedit [your ign] [slot] ability:_" or "_/pokeedit [your ign] [slot] ab_"
and hit tab to auto-complete an ability and then run the command.

**What version of Pixelmon and Forge are you on?**
Latest Technic - 8.4.2

**Please provide any screenshots or crash reports if needed.**
![ability pokeedit](https://user-images.githubusercontent.com/81582380/113617571-56343200-960b-11eb-8463-1ec7d678c40a.png)
![ab pokeedit](https://user-images.githubusercontent.com/81582380/113618985-3e5dad80-960d-11eb-857f-a4d6783b5a2a.PNG)

**Comment by Stampede2011** [comment]
Fixed!
