### ISSUE TITLE
Sometimes, claiming loot chests bugs out and nothing is redeemed.

### ISSUE THREAD

**Issue by Lukeno94** [Dysth/Generations#98]
**What is the bug?**
Sometimes, when you go to claim a Pokeloot chest (of any type, doesn't matter which one - although I feel like I've encountered it most often with ultra loot chests on the first case), it will give you no items at all - no GUI, no message, nothing. If it is a timed loot or a one-claim-per-player loot, you'll then see the "you already claimed this" message. However, this will then persist across all other loot chests for the remainder of the session for that player (relogging sometimes fixes, but doesn't always - staying offline for a while might do so), and I also believe it may affect all other loot GUIs; I know for a fact it affects the Max Powder beam, and I also think this is the cause of mega bosses sometimes not dropping loot or even displaying the GUI that we hear about from time to time.

Annoyingly, there is no obvious log response for it, and the actual trigger could be happening way before you even come to a loot chest as a result.

**What are the steps to reproduce the bug?**
This is a tricky one; I haven't found any way to easily reproduce it, but I know for a fact I'll encounter this every now and again and other players on Harmony report this exact issue.

**What version of Pixelmon and Forge are you on?**
Generations 8.4.2 and Forge 2854

**Please provide any screenshots or crash reports if needed.**
I don't have any at present, but if I encounter it again I will put a video up showing exactly what happens.

**Comment by Deltric** [comment]
This sounds more like a plugin conflict of some sort rather than a mod bug. I've never once seen this in singleplayer or experienced this in multiplayer myself on multiple different servers and have asked other server owners.
